### PR TITLE
Fix returning timeout errors when pipe is closed

### LINKED ISSUE #7709: The consume API should return an immediate error when pipe is closed
### Description

When a `pipe` instance gets closed while the `consume` API is invoked, it currently returns a timeout error after the given timeout passes. Instead, the `consume` API should immediately return an error stating that the pipe has been closed.

### Steps to Reproduce

1. Execute the following code.

```ballerina
import ballerina/io;
import ballerina/lang.runtime;
import xlibb/pipe;

public function main() returns error? {
    pipe:Pipe pipe = new(5);

    worker A {
        runtime:sleep(5);
        Error? close = pipe.gracefulClose(timeout = 5);
        test:assertTrue(close is ());
    }
    worker B {
        Error? consumedValue = pipe.consume(20);
        if consumedValue is Error {
            io:println(consumedValue.message());
        }
    }
    wait B;
}
```

2. Observe the log output stating as the timeout has exceeded.

### Version

2201.11.0 

### Environment Details (with versions)

_No response_

### PR DESCRIPTION
**Pull request by Nuvindu**
## Purpose

Fixes: https://github.com/ballerina-platform/ballerina-library/issues/7709

## Checklist
- [ ] Linked to an issue
- [ ] Updated the changelog
- [ ] Added tests
- [ ] Updated the spec

### CODE REVIEW

File: native/src/main/java/io/xlibb/pipe/Pipe.java [hunk 1]
```diff
@@ -297,11 +306,17 @@ protected Observable getTimeKeeper() {
         return timeKeeper;
     }
 
+    protected Observable getCloseObservable() {
+        return closure;
+    }
+
+
```
Comment (MohamedSabthar) [inline native/src/main/java/io/xlibb/pipe/Pipe.java]: Let's remove the extra blank line

**Review by MohamedSabthar — APPROVED** [review]

**Review by ThisaruGuruge — APPROVED** [review]
